feat: enhance group generation and introduce identity for connections
integration-os/integrationos pull request #161
Opened 2024-09-24 17:17 UTC by paulkr

2024-09-25 16:41 UTC, sagoez requested changes

2024-09-25 16:41 UTC, sagoez commented on integrationos-api/src/logic/connection.rs
> +        Environment::Test => format!("{} sandbox account", connection_config.name),
```suggestion
        Environment::Test | Environment::Development => format!("{} sandbox account", connection_config.name),
```

2024-09-25 16:41 UTC, sagoez commented on integrationos-api/src/logic/connection.rs
> +        Environment::Live => format!("{} production account", connection_config.name),
```suggestion
        Environment::Live | Environment::Production => format!("{} production account", connection_config.name),
```

2024-09-25 16:41 UTC, sagoez commented on integrationos-api/src/logic/connection.rs
> +        Environment::Production => format!("{} production account", connection_config.name),
```suggestion
```

2024-09-25 16:41 UTC, sagoez commented on integrationos-api/src/logic/connection.rs
> +        Environment::Development => format!("{} sandbox account", connection_config.name),
```suggestion
```

2024-09-25 16:41 UTC, sagoez commented on integrationos-api/src/logic/oauth.rs
> +        Environment::Test => format!("{} sandbox account", conn_definition.name),
DITTO. Optionally if this is repeated perhaps we could put this in a single place?

2024-09-25 16:41 UTC, sagoez commented on integrationos-api/tests/api_tests/test_server/mod.rs
> +        let (key, _access_key) = match environment {
```suggestion
        let (key, _) = match environment {
```

2024-09-26 17:57 UTC, sagoez approved these changes

2024-09-27 17:53 UTC, sagoez approved these changes

2024-09-30 15:04 UTC, moekatib approved these changes

2024-09-30 15:06 UTC, merged