feat: add supported status to connection model definition
integration-os/integrationos pull request #50
Opened 2024-05-29 17:05 UTC by paulkr

2024-05-29 17:15 UTC, samgj18 requested changes

2024-05-29 17:15 UTC, samgj18 commented on integrationos-unified/src/unified.rs
> +                "Connection Model Definition is not verified.",
Let’s return an ApplicationError::not_found

2024-05-29 18:50 UTC, samgj18 approved these changes

2024-05-30 15:58 UTC, moekatib approved these changes

2024-05-30 15:58 UTC, merged